import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Toaster } from "sonner";
import { BotProvider } from "../context/BotContext";
import { Header, MobileNav } from "../components/layout";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <BotProvider>
          <Header />
          <main className="pb-24 pt-16 md:pb-8 md:pt-16">{children}</main>
          <MobileNav />
          <Toaster theme="dark" toastOptions={{ style: { background: '#0a0a0f', border: '1px solid rgba(255,255,255,0.1)', color: 'white' } }} />
        </BotProvider>
      </body>
    </html>
  );
}
